image: node:latest

stages:
  - install
  - build
  - test
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - cache/Cypress
    - node_modules
    - build


install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/

bundle_app:
  stage: build
  script:
    - npm run build

e2eTest:
  stage: test
  only:
    - main
  image: cypress/browsers:node18.12.0-chrome106-ff106
  script:
    - echo "Run tests in headless mode"
    - npx serve -s ./build  -l 3000  &
    - npx cypress run --browser chrome